/*CRIAR A DATABASE crud2 */

CREATE TABLE usuarios (
  id_usuario INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
  nome VARCHAR(100) NOT NULL,
  email VARCHAR(100) NOT NULL,
  senha VARCHAR(100) NOT NULL  
);